load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["baz.go"],
    importpath = "github.com/google/wire/internal/wire/testdata/FieldsOfImportedStruct/baz",
    visibility = ["//:__subpackages__"],
)
